### ISSUE TITLE
[python threads]  - die on the N of errors in any thread

### ISSUE THREAD

**Issue by mur-me** [bifrost-platform/bifrost-relayer#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now, you have code that will try to restart application on and on like here:
https://github.com/bifrost-platform/bifrost-relayer/blob/ee9000949cdab085bcba4b709efb32df1b475683/relayer/chainpy/eventbridge/eventbridge.py#L235-L251

But we already faced situation when sender_th thread was dead in relayer app and it were restrarted 50(!) times until @seonggwonyoon pinged me and other problematic relayers in the Discord. 

**50*60==3000 second or 50 minutes my relayer was down.**

### Expected Behavior

My suggestions change code https://github.com/bifrost-platform/bifrost-relayer/blob/ee9000949cdab085bcba4b709efb32df1b475683/relayer/chainpy/eventbridge/eventbridge.py#L235-L251:
1. Add some retries counter with small threshold, e.x. 3
2. Add one more if with threshold check
3. Die with `sys.exit(1)` if threshold violated

Why this should work:
* docker-compose case - there is `restart:always` policy on the relayer container 
* simple docker case - `docker run --always `
* systemd case - `Restart=always` on the service - need to be updated in your docu

### Steps to Reproduce

Somehow make any monitoring or sender thread unactive

### Environment

- Operating Environment: ubuntu 22
- Node Version: v1.0.7
- Execution Method: Docker, Systemd will be the same

**Comment by mur-me** [comment]
Hey, @seonggwonyoon, can you please take a look on this?

**Comment by dongchangYoo** [comment]
The main reason why the relayer is down is the stability issue of the RPC endpoints. If the stopped relayer turns on right away, it will probably stop right away. Therefore, the relayer needs some delay before it restarts. (Expecting to ease endpoint issues)
 
In addition, It is also effective for the transaction sender to have a little delay before re-run. This is to wait for the network traffic to be alleviated if the transaction was pended to the mempool.

**Comment by dongchangYoo** [comment]
However, the policy that restarts outside the Python program can be applied against the main process terminated for unexpected reasons. I think this will help stabilize the BIFROST network more in the future. Thank you.
