### ISSUE TITLE
I want to run relayer.. how to fix this error?

### ISSUE THREAD

**Issue by Palsy** [bifrost-platform/bifrost-relayer#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

23-04-01 14:29:27 [HeartBeat-] 0x83861435:BFC_MAIN:HeartBeat(False)
23-04-01 14:29:27 [CheckRound] 0x83861435:BFC_MAIN:VSPFeed:cached(158):fetched(158)
23-04-01 14:29:27 [CheckAuth-] 0x83861435:BFC_MAIN:CheckMyEvent:RelayerIdxCache: []
23-04-01 14:29:27 [UpdateAuth] 0x83861435:BFC_MAIN:CheckMyEvent:FetchRelayerIdx:round(152):index(None)
23-04-01 14:29:27 [UpdateAuth] 0x83861435:BFC_MAIN:CheckMyEvent:IgnoreRequest:['BFC_MAIN', 152, 1431]:EXECUTED
23-04-01 14:29:32 [---Evm----] 0x83861435:BFC_MAIN:RelayerHeartBeat:EvmError:[BFC_MAIN] revert Dispatched call failed with error: Module(ModuleError { index: 20, error: [3, 0, 0, 0], message: Some("RelayerDNE") })
23-04-01 14:29:32 [HeartBeat-] 0x83861435:BFC_MAIN:HeartBeat(False)

23-04-01 14:30:02 [---Evm----] 0x83861435:BFC_MAIN:RelayerHeartBeat:EvmError:[BFC_MAIN] revert Dispatched call failed with error: Module(ModuleError { index: 20, error: [3, 0, 0, 0], message: Some("RelayerDNE") })
23-04-01 14:30:02 [HeartBeat-] 0x83861435:BFC_MAIN:HeartBeat(False)
23-04-01 14:30:04 [CheckRound] 0x83861435:BFC_MAIN:VSPFeed:cached(158):fetched(158)
23-04-01 14:30:32 [---Evm----] 0x83861435:BFC_MAIN:RelayerHeartBeat:EvmError:[BFC_MAIN] revert Dispatched call failed with error: Module(ModuleError { index: 20, error: [3, 0, 0, 0], message: Some("RelayerDNE") })
23-04-01 14:30:32 [HeartBeat-] 0x83861435:BFC_MAIN:HeartBeat(False)
23-04-01 14:31:02 [---Evm----] 0x83861435:BFC_MAIN:RelayerHeartBeat:EvmError:[BFC_MAIN] revert Dispatched call failed with error: Module(ModuleError { index: 20, error: [3, 0, 0, 0], message: Some("RelayerDNE") })
23-04-01 14:31:02 [HeartBeat-] 0x83861435:BFC_MAIN:HeartBeat(False)
23-04-01 14:31:03 [CheckRound] 0x83861435:BFC_MAIN:VSPFeed:cached(158):fetched(158)
23-04-01 14:31:25 [--Bridge--] 0x83861435:NONE_CHAIN:ThreadHealthCheck:Check the survival of the threads every 60 seconds.

----

how to fix ModuleError  ?

**Comment by dnjscksdn98** [comment]
Your relayer address must be active for the current round and also registered to the blockchain.

**Comment by Palsy** [comment]
답변 감사합니다.

현재 베이직노드에서 풀노드로 전환하려는 상태이고,
아카이브모드 RPC endpoint들을 다 entity.relayer.private.json 에 기입한 상태이고, 콜도 잘 불리는걸 확인했습니다.
Substrate portal로 릴레이어 계정을 옵션에 추가하여 SetValidatorTier 를 실행하였는데에도 위와 같은 에러가 발생합니다.

가이드문서에는 릴레이어 계정을 따로 등록하거나 하는 절차가 보이지 않는데요, 제가 놓친 부분이 있을까요?

**Comment by dnjscksdn98** [comment]
노드가 정상적으로 풀노드로 전환이 되었는지 다시 한번 확인 부탁드리고, 다음 라운드까지 한번 대기한 후에도 다시한번 확인 부탁드리겠습니다.

**Comment by Palsy** [comment]
한 라운드 대기해봐야겠네요 !! 늦은 밤에 답변 감사합니다
